"""
Helper functions to improve readability of model-generated text
"""

import re


def clean_children_gpt2(model_text):
    """
    Clean text generated by GPT2 fine-tuned on the bAbI CPT text
    """

    model_text = re.sub(r"`` ", '"', model_text)
    model_text = re.sub(r"` ", "'", model_text)
    model_text = re.sub(r" ''", '"', model_text)
    model_text = re.sub(r" '", "'", model_text)

    return model_text

